// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using database;

namespace database.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("database.Esame", b =>
                {
                    b.Property<int>("IdEsame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEsame")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudenteForeignKey")
                        .HasColumnType("int");

                    b.Property<int?>("StudenteKeyIdStudente")
                        .HasColumnType("int");

                    b.Property<int>("VotoEsame")
                        .HasColumnType("int");

                    b.HasKey("IdEsame");

                    b.HasIndex("StudenteKeyIdStudente");

                    b.ToTable("Esami");
                });

            modelBuilder.Entity("database.Studente", b =>
                {
                    b.Property<int>("IdStudente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudenteIdStudente")
                        .HasColumnType("int");

                    b.HasKey("IdStudente");

                    b.HasIndex("StudenteIdStudente");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("database.Esame", b =>
                {
                    b.HasOne("database.Studente", "StudenteKey")
                        .WithMany()
                        .HasForeignKey("StudenteKeyIdStudente");
                });

            modelBuilder.Entity("database.Studente", b =>
                {
                    b.HasOne("database.Studente", null)
                        .WithMany("Studenti")
                        .HasForeignKey("StudenteIdStudente");
                });
#pragma warning restore 612, 618
        }
    }
}
